[package]
name = "tidy"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
autobins = false

[dependencies]
cargo_metadata = "0.11"
regex = "1"
lazy_static = "1"
walkdir = "2"
crossbeam-utils = "0.8.0"

[[bin]]
name = "rust-tidy"
path = "src/main.rs"
