# The service providing the commit statuses to GitHub.
status = ["buildbot/yorick-buildbot-build-script-hw"]

# Allow eight hours for builds + tests.
timeout_sec = 28800

# Have bors delete auto-merged branches
delete_merged_branches = true

# Don't include PR description in merge commit.
cut_body_after = ""
