[package]
authors = ["The Rust Project Developers"]
name = "rust-demangler"
version = "0.0.1"
edition = "2018"

[dependencies]
regex = "1.0"
rustc-demangle = "0.1.17"

[lib]
name = "rust_demangler"
doctest = false

[[bin]]
name = "rust-demangler"
test = false
