[package]
name = "rustdoc-json-types"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
